import express from 'express';
import {readFileSync} from 'node:fs';
import {settings,random,hash,equal,sign,verify,cookies,esc} from './lib/security.mjs';
import {redisStore,discordProvider,emailProvider} from './lib/providers.mjs';
// Explicit file reads let Vercel trace the protected files into the function bundle.
// There is deliberately no public/ directory and no static CDN route.
const branding=new Map([
 ['/logo.png',{type:'image/png',body:readFileSync(new URL('./protected/logo.png',import.meta.url))}],
 ['/favicon.svg',{type:'image/svg+xml',body:readFileSync(new URL('./protected/favicon.svg',import.meta.url))}],
]);
const assets=new Map([
 ['/',{type:'text/html; charset=utf-8',body:readFileSync(new URL('./protected/index.html',import.meta.url))}],
 ['/index.html',{type:'text/html; charset=utf-8',body:readFileSync(new URL('./protected/index.html',import.meta.url))}],
 ['/policy-ui.css',{type:'text/css; charset=utf-8',body:readFileSync(new URL('./protected/policy-ui.css',import.meta.url))}],
 ['/favicon.svg',{type:'image/svg+xml',body:readFileSync(new URL('./protected/favicon.svg',import.meta.url))}],
 ['/catalog.json',{type:'application/json; charset=utf-8',body:readFileSync(new URL('./protected/catalog.json',import.meta.url))}],
 ['/js/app.mjs',{type:'text/javascript; charset=utf-8',body:readFileSync(new URL('./protected/js/app.mjs',import.meta.url))}],
 ['/js/policy.mjs',{type:'text/javascript; charset=utf-8',body:readFileSync(new URL('./protected/js/policy.mjs',import.meta.url))}],
]);
const page=(title,content)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · Venom</title><link rel="icon" href="/favicon.svg"><style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#eef2fa;color:#27344b;font:16px/1.6 "Segoe UI",Arial,sans-serif}main{width:min(90%,650px);padding:36px;background:white;border-radius:18px;box-shadow:0 10px 45px #20306016;box-sizing:border-box}h1{font-size:28px;font-weight:700;letter-spacing:-.02em;line-height:1.2;color:#243fa4}a,button{display:inline-block;background:#2459ed;color:white;border:0;padding:12px 18px;border-radius:8px;text-decoration:none;font:600 16px "Segoe UI",Arial,sans-serif;cursor:pointer;margin:6px 6px 6px 0}.muted{color:#68778e}button.reject{background:#9b3345}input{font:inherit;padding:8px;width:100%;box-sizing:border-box;border:1px solid #bbc4d4;border-radius:6px}table{width:100%;border-collapse:collapse}td,th{padding:8px;text-align:left;border-bottom:1px solid #ddd;overflow-wrap:anywhere}code{overflow-wrap:anywhere}.user{margin:20px 0;padding:16px;background:#f3f5fb;border-radius:8px}form{display:inline-block}small{font-size:14px}</style></head><body><main><img src="/logo.png" alt="Lifeinvader" style="display:block;width:min(100%,320px);height:auto;margin-bottom:24px"><h1>${esc(title)}</h1>${content}</main></body></html>`;
const form=(action,csrf,label)=>`<form method="post" action="${action}"><input type="hidden" name="csrf" value="${esc(csrf)}"><button>${label}</button></form>`;
export function createApp(deps={}){
 const env=deps.env||process.env;const app=express();app.disable('x-powered-by');app.use(express.urlencoded({extended:false,limit:'8kb'}));let store=deps.store,discord=deps.discord,mailer=deps.mailer;
 app.use((req,res,next)=>{res.set({'Cache-Control':'private, no-store, max-age=0','CDN-Cache-Control':'no-store','Vercel-CDN-Cache-Control':'no-store','Referrer-Policy':'same-origin','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; form-action 'self'; base-uri 'none'"});if(['GET','HEAD'].includes(req.method)&&branding.has(req.path)){const asset=branding.get(req.path);return res.type(asset.type).send(asset.body);}try{req.config=settings(env);store||=redisStore(env);discord||=discordProvider(env);mailer||=emailProvider(env);next();}catch{res.status(503).send(page('Access setup is incomplete','<p>The owner needs to finish the Discord and approval-email setup. Access stays closed until it is configured.</p>'));}});
 const cookieOpts=req=>({httpOnly:true,secure:req.config.secure,sameSite:'lax',path:'/'});
 async function getSession(req){const value=cookies(req)[req.config.sessionCookie];if(!value||!/^[A-Za-z0-9_-]{43}$/.test(value))return null;const s=await store.get('venom:session:'+hash(value));return s?.expires>Date.now()?s:null;}
 async function status(req,s){return req.config.admins.includes(s.user.id)?'approved':(await store.get('venom:access:'+s.user.id))?.status||'pending';}
 function origin(req){return req.headers.origin===req.config.origin;}
 function csrf(req,s){return origin(req)&&s&&equal(req.body.csrf,s.csrf);}
 async function notification(req,record){if(record.status!=='pending')return;const key='venom:mail:'+record.user.id;if(!await store.setNX(key,true,86400))return false;try{const token=sign({type:'approval',id:record.user.id,nonce:record.nonce,exp:Date.now()+72*3600000},req.config.secret);await mailer.request(record.user,req.config.origin+'/review?token='+encodeURIComponent(token),record.nonce);await store.set('venom:mail-status:'+record.user.id,{sentAt:Date.now()});return true;}catch(e){await store.del(key);throw e;}}
 app.get('/login',async(req,res)=>{const s=await getSession(req);if(s&&await status(req,s)==='approved')return res.redirect('/');res.send(page('Sign in with Discord','<p>Only approved Discord accounts can use this app.</p><p>New requests are sent to the owner for approval by email. Your Discord username and user ID are included in that request.</p><a href="/auth/discord">Continue with Discord</a>'));});
 app.get('/auth/discord',async(req,res)=>{const state=random();const ip=hash(req.headers['x-real-ip']||req.socket.remoteAddress||'unknown');if(await store.increment('venom:rate:'+ip,600)>30)return res.status(429).send(page('Please wait','<p>Too many sign-in attempts. Try again in 10 minutes.</p>'));await store.set('venom:oauth:'+hash(state),true,600);res.cookie(req.config.stateCookie,state,{...cookieOpts(req),maxAge:600000});const u=new URL('https://discord.com/oauth2/authorize');u.search=new URLSearchParams({client_id:env.DISCORD_CLIENT_ID,response_type:'code',redirect_uri:req.config.origin+'/auth/discord/callback',scope:'identify',state,prompt:'consent'}).toString();res.redirect(u.href);});
 app.get('/auth/discord/callback',async(req,res)=>{const state=req.query.state;const saved=cookies(req)[req.config.stateCookie];res.clearCookie(req.config.stateCookie,cookieOpts(req));if(typeof state!=='string'||!equal(state,saved)||!await store.take('venom:oauth:'+hash(state)))return res.status(400).send(page('Sign-in could not be verified','<p>The sign-in link expired or could not be verified.</p><a href="/login">Try again</a>'));if(typeof req.query.code!=='string'||req.query.error)return res.redirect('/login');const user=await discord.identify(req.query.code,req.config.origin+'/auth/discord/callback');if(!/^\d{17,20}$/.test(user.id))throw Error('Invalid Discord identity');const old=cookies(req)[req.config.sessionCookie];if(old)await store.del('venom:session:'+hash(old));const sid=random();const session={user,csrf:random(),expires:Date.now()+7*86400000};await store.set('venom:session:'+hash(sid),session,7*86400);res.cookie(req.config.sessionCookie,sid,{...cookieOpts(req),maxAge:7*86400000});if(!req.config.admins.includes(user.id)){const fresh={user,status:'pending',nonce:random(),requestedAt:Date.now()};await store.setNX('venom:access:'+user.id,fresh);await store.addUser(user.id);const r=await store.get('venom:access:'+user.id);try{await notification(req,r);}catch{return res.redirect('/account?mail=failed');}}res.redirect('/');});
 app.get('/account',async(req,res)=>{const s=await getSession(req);if(!s)return res.redirect('/login');const state=await status(req,s);const mailStatus=state==='pending'?await store.get('venom:mail-status:'+s.user.id):null;const description={pending:'Your request is waiting for the owner’s approval. Check again after the owner approves it.',approved:'Your Discord account is approved.',rejected:'The owner rejected this request. Contact the owner if this was a mistake.',revoked:'Access to this account has been revoked.'}[state]||'Access is not approved.';res.send(page('Your access',`<p><b>${esc(s.user.displayName)}</b> (@${esc(s.user.username)})</p><p>Discord ID: <code>${esc(s.user.id)}</code></p><p><b>${esc(state.charAt(0).toUpperCase()+state.slice(1))}</b></p><p>${description}</p>${state==='pending'?(mailStatus?'<p class="muted">Approval email sent. You can send another request after 24 hours.</p>':'<p class="muted">Email delivery has not been confirmed. Use Send approval request to retry.</p>'):''}${req.query.mail==='failed'?'<p>The approval email could not be sent. Try the request button again or contact the owner.</p>':''}${state==='approved'?'<a href="/">Open ad creator</a>':'<a href="/account">Check approval</a>'}${state==='pending'?form('/request-email',s.csrf,'Send approval request'):state==='revoked'?form('/request-email',s.csrf,'Request access again'):''}${req.config.admins.includes(s.user.id)?'<a href="/admin">Manage access</a>':''}${form('/logout',s.csrf,'Sign out')}`));});
 app.post('/request-email',async(req,res)=>{const s=await getSession(req);if(!csrf(req,s))return res.status(403).send(page('Request refused','<p>Sign in again and use the request button on your account page.</p>'));let record=await store.get('venom:access:'+s.user.id);if(record?.status==='revoked'){await store.reopen(s.user.id,random());record=await store.get('venom:access:'+s.user.id);}if(!record||record.status!=='pending')return res.redirect('/account');try{const sent=await notification(req,record);res.send(page(sent?'Approval request sent':'Request already sent',sent?'<p>Your approval request was emailed to the owner.</p><a href="/account">My access</a>':'<p>An approval request was already sent within the last 24 hours. Please wait for the owner’s decision.</p><a href="/account">My access</a>'));}catch{res.status(502).send(page('Email could not be sent','<p>Contact the owner or try again later. Your account remains blocked.</p><a href="/account">My access</a>'));}});
 async function requestFromToken(req){const t=verify(req.method==='POST'?req.body.token:req.query.token,req.config.secret,'approval');if(!t||!/^\d{17,20}$/.test(t.id)||typeof t.nonce!=='string')return null;const r=await store.get('venom:access:'+t.id);return r&&r.status==='pending'&&equal(r.nonce,t.nonce)?{token:t,record:r}:null;}
 app.get('/review',async(req,res)=>{const r=await requestFromToken(req);if(!r)return res.status(410).send(page('Request link is no longer active','<p>This link expired or the request has already been decided. Use the administrator page or ask the user to resend their pending request.</p>'));res.send(page('Approve this Discord account?',`<p><b>${esc(r.record.user.displayName)}</b> (@${esc(r.record.user.username)})</p><p>Discord ID: <code>${esc(r.record.user.id)}</code></p><p>Approval grants access only to this Discord ID.</p><form method="post" action="/review"><input type="hidden" name="token" value="${esc(req.query.token)}"><button name="decision" value="approved">Approve</button><button class="reject" name="decision" value="rejected">Reject</button></form>`));});
 app.post('/review',async(req,res)=>{if(!origin(req)||!['approved','rejected'].includes(req.body.decision))return res.status(403).send(page('Request refused','<p>Open the private review link from your email and use its buttons.</p>'));const r=await requestFromToken(req);if(!r||!await store.decide(r.token.id,r.token.nonce,req.body.decision))return res.status(410).send(page('Request already decided','<p>This approval link is expired or has already been used.</p>'));res.send(page(req.body.decision==='approved'?'Access approved':'Access rejected',`<p>Discord ID <code>${esc(r.token.id)}</code> is now ${esc(req.body.decision)}.</p><p>${req.body.decision==='approved'?'They can refresh their access page to enter the app.':'They cannot enter the app.'}</p>`));});
 app.post('/logout',async(req,res)=>{const s=await getSession(req);if(!csrf(req,s))return res.sendStatus(403);await store.del('venom:session:'+hash(cookies(req)[req.config.sessionCookie]));res.clearCookie(req.config.sessionCookie,cookieOpts(req));res.redirect('/login');});
 app.get('/admin',async(req,res)=>{const s=await getSession(req);if(!s)return res.redirect('/login');if(!req.config.admins.includes(s.user.id))return res.sendStatus(403);const ids=await store.users();const records=(await Promise.all(ids.slice(0,500).map(id=>store.get('venom:access:'+id)))).filter(Boolean);const row=r=>`<div class="user"><b>${esc(r.user.displayName)}</b> (@${esc(r.user.username)})<br><code>${esc(r.user.id)}</code> — ${esc(r.status.charAt(0).toUpperCase()+r.status.slice(1))}<br><form method="post" action="/admin/decision"><input type="hidden" name="csrf" value="${esc(s.csrf)}"><input type="hidden" name="id" value="${esc(r.user.id)}">${r.status!=='approved'?'<button name="decision" value="approved">Approve</button>':''}${r.status==='approved'?'<button class="reject" name="decision" value="revoked">Revoke</button>':''}</form></div>`;const section=(label,statuses)=>{const list=records.filter(r=>statuses.includes(r.status));return `<section><h2>${label} (${list.length})</h2>${list.length?list.map(row).join(''):'<p class="muted">No users in this section.</p>'}</section>`;};res.send(page('Manage access',`<p>Review new requests or manage existing access.</p>${section('New requests',['pending'])}${section('Users with access',['approved'])}${section('Revoked or rejected',['revoked','rejected'])}<a href="/account">My access</a>`));});
 app.post('/admin/decision',async(req,res)=>{const s=await getSession(req);if(!csrf(req,s)||!req.config.admins.includes(s.user.id)||!/^\d{17,20}$/.test(req.body.id)||!['approved','revoked'].includes(req.body.decision))return res.sendStatus(403);const r=await store.get('venom:access:'+req.body.id);if(!r)return res.sendStatus(404);await store.set('venom:access:'+req.body.id,{...r,status:req.body.decision,nonce:null,decidedAt:Date.now()});res.redirect('/admin');});
 app.use(async(req,res)=>{if(!['GET','HEAD'].includes(req.method))return res.sendStatus(405);const s=await getSession(req);if(!s)return req.path==='/'?res.redirect('/login'):res.status(401).send('Discord sign-in required.');if(await status(req,s)!=='approved')return req.path==='/'?res.redirect('/account'):res.status(403).send('Your Discord account is not approved.');const asset=assets.get(req.path);if(!asset)return res.sendStatus(404);res.type(asset.type).send(asset.body);});
 app.use((err,req,res,next)=>{if(res.headersSent)return next(err);console.error('Venom authentication request failed');res.status(503).send(page('Unable to verify access','<p>Sign-in or approval services are temporarily unavailable. Access stays closed.</p><a href="/login">Try sign-in again</a>'));});return app;
}
export default createApp();
