import {randomBytes,createHmac,timingSafeEqual,createHash} from 'node:crypto';
export const random=()=>randomBytes(32).toString('base64url');
export const hash=s=>createHash('sha256').update(s).digest('hex');
export const equal=(a,b)=>typeof a==='string'&&typeof b==='string'&&Buffer.byteLength(a)===Buffer.byteLength(b)&&timingSafeEqual(Buffer.from(a),Buffer.from(b));
export const sign=(data,secret)=>{const payload=Buffer.from(JSON.stringify(data)).toString('base64url');return payload+'.'+createHmac('sha256',secret).update(payload).digest('base64url');};
export function verify(token,secret,type){try{if(typeof token!=='string'||token.length>2048)return null;const [p,s,...rest]=token.split('.');if(rest.length||!equal(s,createHmac('sha256',secret).update(p).digest('base64url')))return null;const d=JSON.parse(Buffer.from(p,'base64url').toString());if(d.type!==type||!Number.isFinite(d.exp)||d.exp<=Date.now())return null;return d;}catch{return null;}}
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function cookies(req){const out={};for(const pair of (req.headers.cookie||'').split(';')){const i=pair.indexOf('=');if(i>0){const key=pair.slice(0,i).trim();if(!Object.hasOwn(out,key))try{out[key]=decodeURIComponent(pair.slice(i+1));}catch{}}}return out;}
export function settings(env){const required=['APP_URL','DISCORD_CLIENT_ID','DISCORD_CLIENT_SECRET','SESSION_SECRET','UPSTASH_REDIS_REST_URL','UPSTASH_REDIS_REST_TOKEN','RESEND_API_KEY','MAIL_FROM','APPROVAL_EMAIL'];if(required.some(k=>!env[k]||/replace_me|your_/i.test(env[k])))throw Error('Setup incomplete');const u=new URL(env.APP_URL);if(u.pathname!=='/'||u.search||u.hash||u.username||u.password||u.protocol!=='https:'&&!(env.NODE_ENV!=='production'&&['localhost','127.0.0.1'].includes(u.hostname)))throw Error('Invalid APP_URL');if(env.SESSION_SECRET.length<64)throw Error('Session secret too short');if(!/^\d{17,20}$/.test(env.DISCORD_CLIENT_ID))throw Error('Invalid Discord client ID');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(env.APPROVAL_EMAIL))throw Error('Invalid approval email');const admins=(env.ADMIN_DISCORD_IDS||'').split(',').map(s=>s.trim()).filter(Boolean);if(admins.some(id=>!/^\d{17,20}$/.test(id)))throw Error('Invalid administrator Discord ID');return {origin:u.origin,secure:u.protocol==='https:',secret:env.SESSION_SECRET,sessionCookie:u.protocol==='https:'?'__Host-venom-session':'venom-session',stateCookie:u.protocol==='https:'?'__Host-venom-oauth':'venom-oauth',admins};}
