import {makeAd,businesses,locations} from './policy.mjs';
let catalog,category='vehicle',state={},last=null;
const app=document.getElementById('app');const sections={vehicle:['Vehicle Ads','Vehicle Ads Creator','Auto'],property:['House Ads','House Ads Creator','Real Estate'],clothing:['Clothing Ads','Clothing Ads Creator','Other'],items:['Items Ads','Item Ads Creator','Other'],business:['Business Ads','Business Ads Creator','Businesses'],rules:['Policies','Policies & Catalogue','']};
const icons={vehicle:'▣',property:'⌂',clothing:'◇',items:'□',business:'▥',rules:'≡'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const opts=(arr,value='')=>arr.map(x=>{const val=typeof x==='object'?x.value:x;const label=typeof x==='object'?x.label:x;return `<option value="${esc(val)}" ${String(value)===String(val)?'selected':''}>${esc(label)}</option>`;}).join('');
function input(key,label,value='',hint='',extra=''){return `<div class="field"><label for="${key}">${label}</label><input id="${key}" data-key="${key}" value="${esc(value)}" ${extra}>${hint?'<small>'+hint+'</small>':''}</div>`;}
function select(key,label,arr,value='',hint=''){return `<div class="field"><label for="${key}">${label}</label><select id="${key}" data-key="${key}">${opts(arr,value)}</select>${hint?'<small>'+hint+'</small>':''}</div>`;}
function check(key,label,checked=false){return `<label class="check"><input type="checkbox" data-key="${key}" ${checked?'checked':''}>${label}</label>`;}
function choices(key,label,arr,value,multiple=false){return `<fieldset class="field"><legend>${label}</legend><div class="choices">${arr.map(a=>`<button type="button" class="choice" data-choice="${key}" data-value="${esc(a)}" data-multiple="${multiple}" aria-pressed="${multiple?(value||[]).includes(a):value===a}">${esc(a)}</button>`).join('')}</div></fieldset>`;}
function catalogue(key,label,records,value='',hint=''){const id=key+'-list';const unique=[...new Set(records.map(r=>r.name))].sort((a,b)=>a.localeCompare(b));return input(key,label,value,hint,`list="${id}" placeholder="Search the Excel catalogue…" autocomplete="off"`)+`<datalist id="${id}">${opts(unique)}</datalist>`;}
const price=(key='price',value='')=>input(key,'Price / Budget (optional)',value,'Examples: 250000, 250k, 4.5m or Negotiable.');
function defaults(c){return {mode:c==='property'||c==='business'?'Selling':'Buying',kind:'car',type:'house',count:'1',items:[{name:'',quantity:'',price:'',gender:''}]};}
function open(c){category=c;state=defaults(c);last=null;render();document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.category===c));}
function render(){if(category==='rules'){renderRules();return;}let body='';
const modes=category==='property'?['Selling','Buying','Renting out','Looking to rent']:category==='business'?['Selling','Buying']:['Buying','Selling','Selling or trading','Trading'];body+=choices('mode','Transaction Type',modes,state.mode);
if(category==='vehicle'){
 body+=select('kind','Vehicle Category',['car','electric car','motorcycle','boat','plane','helicopter'],state.kind);
 body+=`<div class="field">${check('generic','Advertise a general vehicle without a model',state.generic)}</div>`;
 if(!state.generic)body+=catalogue('name',state.mode==='Buying'?'Vehicle Name (optional)':'Vehicle Name',catalog.vehicles.filter(r=>state.kind==='electric car'?r.kind==='car':r.kind===state.kind),state.name,state.mode==='Buying'?'Leave blank to buy any vehicle in the selected category. Enter a model to buy a specific vehicle.':'One vehicle per ad. Use a second vehicle only as the trading target.');
 const selectedVehicle=catalog.vehicles.find(r=>r.name===state.name);if(selectedVehicle?.stateValue&&!state.generic)body+=`<p class="notice">Excel state value: $${selectedVehicle.stateValue.toLocaleString('en-US').replaceAll(',','.')}. This is a reference, not a current market price.</p>`;
 if(state.mode.includes('trading')||state.mode==='Trading')body+=catalogue('target','Trade For (optional)',catalog.vehicles,state.target,'Trade only within Auto. Houses, businesses and items cannot be trading targets.');
 body+=select('config','Configuration',[{value:'',label:'Not specified'},'full','partial'],state.config);
 body+=choices('extras','Extras',['visual upgrades','insurance','tuning parts','turbo kit','drift kit'],state.extras,true);
 if(state.mode!=='Trading')body+=price('price',state.price);
}else if(category==='property'){
 body+=`<div class="grid">${select('type','Property / Family',['house','apartment','mansion','Casino penthouse','family','house and apartment'],state.type)}${select('count','Number of Properties',state.type==='family'?['1']:['1','2'],state.count)}</div>`;
 if(!['family','house and apartment'].includes(state.type))body+=input('numbers','Property Numbers (optional)',state.numbers,'Selling/renting out only. For two properties, separate the numbers with a space. Buying requests omit numbers.');
 if(state.type!=='house and apartment')body+=select('family',state.type==='family'?'Family Tier':'Family Included (optional)',[{value:'',label:state.type==='family'?'Not specified':'None'},'family','standard family','advanced family','elite family'],state.family);
 if(!['family','house and apartment'].includes(state.type)){
  body+=`<div class="field">${check('garden','Garden',state.garden)}</div><div class="grid">${select('garage','Garage Spaces',[{value:'',label:'Not specified'},2,5,9,25,30],state.garage)}${select('warehouse','Warehouse Spaces',[{value:'',label:'Not specified'},3,4,5],state.warehouse)}</div>`;
  body+=choices('features','Features',['custom interior','insurance','helipad','tennis court','long driveway','swimming pool'],state.features,true);
  body+=select('view','View',[{value:'',label:'Not specified'},'nice','beautiful','great','good'],state.view);
  body+=select('location','Location',[{value:'',label:'Not specified'},...locations],state.location);
 }
 body+=price('price',state.price);
 if(['Renting out','Looking to rent'].includes(state.mode))body+=select('period','Rental Period',[{value:'',label:'Not specified'},'per day','per week','for 7 days'],state.period);
}else if(category==='business'){
 body+=select('name','Business Type',[{value:'',label:'Select a business'},...businesses],state.name,'One business per ad. Business trading is not permitted.');
 if(state.name==='Plantation')body+=`<div class="grid">${select('beds','Plantation Beds',[{value:'',label:'Not specified'},10,15,20],state.beds)}${select('crop','Crop',[{value:'',label:'Not specified'},'Cabbage','Pineapple','Pumpkin','Mandarin'],state.crop)}</div>`;
 body+=input('number','Business Number (optional)',state.number,'A numbered business uses № and omits the word business.');
 body+=select('location','Location',[{value:'',label:'Not specified'},...locations,'near airport','near mall','in mall'],state.location);body+=price('price',state.price);
}else{
 body+=`<div class="notice">${category==='clothing'?'Clothing, shoes, accessories, watches, sets and backpack skins':'Resources, seeds, fish, pets, gifts and general items'} use the <b>Other</b> category. Choose names from the supplied Excel catalogue.</div>`;
 body+=`<div class="field">${check('bulk','In Bulk (only entries without a quantity)',state.bulk)}</div>`;
 const records=category==='clothing'?catalog.clothing:[...catalog.items,...catalog.clothing];
 state.items.forEach((row,i)=>{let rec=records.find(r=>r.name===row.name);body+=`<div class="row-card" data-row="${i}"><h3>${state.mode==='Trading'?(i===0?'Trading Item':'Trade For'):'Item '+(i+1)}</h3>`;
 body+=catalogue('item-name-'+i,'Name',records,row.name);
 if(rec?.annotation)body+=`<p class="notice">Excel specification: ${esc(rec.raw||rec.annotation)}</p>`;
 if(rec?.detail)body+=`<p class="notice">Classification: ${esc(rec.detail)}</p>`;
 if(rec?.variantKind==='version')body+=input('item-variant-'+i,'Skin Version',row.variant,'Enter the actual version shown on the item. The workbook does not specify a maximum.', 'inputmode="numeric"');
 else if(rec?.variants)body+=select('item-variant-'+i,'Variant',[{value:'',label:'Select a variant'},...rec.variants],row.variant);
 if(category==='clothing'||catalog.clothing.includes(rec)){
  body+=`<div class="grid">${select('item-color-'+i,'Colour',[{value:'',label:'Not specified'},'red','blue','green','black','white','yellow','purple','orange','pink','gray','gold','silver'],row.color)}${input('item-type-'+i,'Type (optional)',row.type,'Classified items already include their exact type.','inputmode="numeric"')}</div>`;
  body+=`<div class="field">${check('item-luminous-'+i,'Luminous',row.luminous)}</div>`;
  const genders=[...new Set(records.filter(r=>r.name===row.name).map(r=>r.gender).filter(Boolean))];
  body+=select('item-gender-'+i,'Gender',[{value:'',label:'Use catalogue gender / unspecified'},...(genders.length?genders:['for men','for women'])],row.gender);
 }
 if(rec?.name==='license plate'){body+=input('item-detail-'+i,'License Plate',row.detail,'One plate per ad. For inappropriate plate text, select Special plate.');body+=`<div class="field">${check('item-special-'+i,'Special plate (omit its text)',row.special)}</div>`;}
 if(rec?.name==='sim-cards')body+=input('item-detail-'+i,'Sim-card Numbers',row.detail,'Maximum two numbers. Format: 11-11-111 22-22-222.');
 body+=input('item-quantity-'+i,'Quantity (optional)',row.quantity,'Leave blank for one item or bulk.','inputmode="numeric"');
 if(state.mode!=='Trading'){body+=price('item-price-'+i,row.price);body+=`<div class="field">${check('item-each-'+i,'Price / Budget is for each item',row.each)}</div>`;}
 body+='</div>';});
 body+=`<div class="actions"><button type="button" id="remove" ${state.items.length<=1||state.mode==='Trading'?'disabled':''}>Remove Item</button><button type="button" id="add" ${state.items.length>=3||state.mode==='Trading'?'disabled':''}>Add Item</button><span style="align-self:center">${state.items.length} of 3</span></div>`;
 if(state.mode==='Selling'){body+=select('market','Market Stall (optional)',[{value:'',label:'No stall'}, {value:'beach',label:'Beach market shop'},{value:'private',label:'Private market stall'}],state.market);
 if(state.market==='beach')body+=input('marketNumber','Beach Market Shop Number',state.marketNumber);
 if(state.market==='private')body+=select('stallLocation','Stall Next To',[{value:'',label:'Select a location'},...locations],state.stallLocation)+input('stallHouse','Or Next To House Number',state.stallHouse);
 if(state.market)body+=`<div class="field">${check('goodPrices','For good prices',state.goodPrices)}</div>`;
 }
}
 app.innerHTML=`<h2>${sections[category][1]}</h2><p class="intro">Create advertisements following LifeInvader guidelines</p><form id="ad-form" novalidate>${body}<div class="actions"><button class="primary" type="submit">Generate Ad</button><button type="button" id="copy" disabled>Copy</button><button type="button" id="reset">Reset</button></div></form><div id="error" role="alert"></div><h3>Output</h3><div id="output">Your advertisement will appear here…</div><div class="output-meta"><span id="ad-category">Category: ${sections[category][2]}</span><span id="count">0 / 150 characters</span></div><div id="warnings"></div><p class="notice">This checks the supported ad formats and catalogue. LI staff must still verify market value, proof of tradeability and any applicable approvals.</p>`;
 document.getElementById('ad-form').addEventListener('submit',e=>{e.preventDefault();generate();});
 app.querySelectorAll('[data-key]').forEach(el=>el.addEventListener(el.type==='checkbox'||el.tagName==='SELECT'?'change':'input',()=>{let key=el.dataset.key;const value=el.type==='checkbox'?el.checked:el.value;let rerender=el.tagName==='SELECT'||el.type==='checkbox';if(key.startsWith('item-')){const [,prop,idx]=key.split('-');state.items[Number(idx)][prop]=value;if(prop==='name')rerender=false;}else {state[key]=value;if(key==='type'){state.count=value==='house and apartment'?'2':'1';state.numbers='';state.family='';state.garden=false;state.garage='';state.warehouse='';state.features=[];state.view='';state.location='';}}invalidate();if(key==='kind')state.name='';if(rerender){render();app.querySelector(`[data-key="${key}"]`)?.focus();}}));
 app.querySelectorAll('input[list]').forEach(el=>el.addEventListener('change',()=>{if(el.dataset.key==='name'){render();}else if(el.dataset.key.startsWith('item-name')){const i=Number(el.dataset.key.split('-').at(-1));state.items[i]={name:el.value,price:state.items[i].price,quantity:state.items[i].quantity};render();}}));
 app.querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.choice,v=b.dataset.value;if(b.dataset.multiple==='true'){const current=state[k]||[];state[k]=current.includes(v)?current.filter(x=>x!==v):[...current,v];}else{state[k]=v;if(k==='mode'&&v==='Trading')state.items=[state.items[0],state.items[1]||{name:''}];}last=null;render();}));
 document.getElementById('add')?.addEventListener('click',()=>{state.items.push({name:''});render();});document.getElementById('remove')?.addEventListener('click',()=>{state.items.pop();render();});
 document.getElementById('reset').addEventListener('click',()=>{state=defaults(category);last=null;render();});document.getElementById('copy').addEventListener('click',copy);
}
function invalidate(){last=null;document.getElementById('copy').disabled=true;document.getElementById('output').textContent='Generate an ad after changing the form.';document.getElementById('count').textContent='0 / 150 characters';document.getElementById('warnings').textContent='';document.getElementById('error').textContent='';}
function generate(){try{last=makeAd(category,state,catalog);document.getElementById('output').textContent=last.text;document.getElementById('count').textContent=`${last.count} / 150 characters`;document.getElementById('ad-category').textContent='Category: '+last.category;document.getElementById('warnings').textContent=[...new Set(last.warnings)].join(' ');document.getElementById('error').textContent='';document.getElementById('copy').disabled=false;return last;}catch(e){last=null;document.getElementById('copy').disabled=true;document.getElementById('output').textContent='Your advertisement will appear here…';document.getElementById('error').textContent=e.message;document.getElementById('count').textContent='0 / 150 characters';return {error:e.message};}}

async function copy(){if(!last)return;try{await navigator.clipboard.writeText(last.text);toast('Copied to clipboard!');}catch{toast('Copy failed. Select the output and copy it manually.');}}
function toast(s){const t=document.getElementById('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200);}
function renderRules(){app.innerHTML=`<h2>Policies & Catalogue</h2><p class="intro">Internal policy last edited 2 October 2026 · March 2026 catalogue</p><div class="notice">The latest internal policy controls editing rules when it differs from the public policy. This app prepares ads; it does not post ads, impose blacklists or verify LI databases.</div><div class="rules">${ruleSections.map(([title,content])=>`<details><summary>${title}</summary>${content}</details>`).join('')}<details><summary>Excel catalogue coverage</summary><p>${catalog.vehicles.length} vehicles, ${catalog.clothing.length} clothing entries and ${catalog.items.length} item entries/variants. Includes cars, motorcycles, boats, planes, helicopters, all nine clothing groups, women's entries and the classification guide.</p><p>State values are reference values, not verified current market prices. Real and in-game brand comparisons are retained below. Some brands have multiple in-game names; choose the exact catalogue item.</p><ul>${catalog.brands.map(b=>`<li>${esc(b.real)}: ${esc(b.game)}</li>`).join('')}</ul></details></div>`;}
const ruleSections=[
 ['Ad format & money','<ul><li>Maximum 150 characters. Selling uses Price, Buying uses Budget, and trading alone has no price. A colon follows Price/Budget.</li><li>Use $ before numbers, periods for thousands and Million/Billion instead of K/M/B. A numeric ending has no full stop; Negotiable, Million and Billion endings do.</li><li>Amounts above $1 Billion become Negotiable except properties and businesses. Houses/apartments below $1 Million become Negotiable. Unrealistic market prices also need staff review.</li><li>Do not mix Auto, Real Estate, Businesses and Other in an ad or trade. Clothing and general items belong to Other.</li></ul>'],
 ['Auto','<p>One vehicle per ad, except a vehicle-to-vehicle trade. Exact brand/model in curly quotes. Order: full/partial configuration, visual upgrades, insurance, tuning parts, turbo kit, drift kit. Use “in configuration”; do not specify insurance days. Max chip tuning becomes full configuration; nearly max becomes partial. Unlisted models require proof of tradeability and HC catalogue approval.</p>'],
 ['Real Estate & families','<p>Maximum two properties, no property trading. Use № for numbers; buying requests cannot target specific numbers. Garage spaces: 2, 5, 9, 25, 30. Warehouse: 3, 4, 5. Order: family, garden, garage, warehouse, custom interior, insurance, other features, view, location. Pluralise features for two properties except insurance. Apartments have no gardens. A mixed house/apartment ad should mention only those property types.</p><p>Villa becomes mansion; Casino apartment becomes Casino penthouse. Renting out uses Rent; Looking to rent uses Budget. Rentals may be per day/per week. Do not mention green zones, gang names/locations or nationalities in interiors.</p><p>One family per ad; omit family names. Advanced/elite families have a listed $10 Million reference value, but staff must assess realistic market prices. A family with a property must be a clearly combined deal.</p>'],
 ['Businesses','<p>One business per ad; Buying/Selling only. Personal becomes private business; drug lab becomes Burger Shop; gun/weapon store becomes Ammunition Store; strip club becomes Bar; Binco/Suburban becomes Clothing Shop. Use the listed capitalisation. Numbered businesses use № and omit “business”. Plantation sizes: 10, 15, 20 beds. Crops: Cabbage, Pineapple, Pumpkin, Mandarin.</p>'],
 ['Other, clothing & special items','<p>Maximum three items. Use the Excel list. Clothing order: colour, luminous, brand, garment, of type, for men/women. Extra becomes of type, rare becomes exclusive and legendary becomes unique. Quantities use periods (1.000), omit in bulk when quantity is given. Pluralise the noun, including irregular forms; mass nouns and plural-only items stay unchanged.</p><p>One license plate; provocative plate text becomes “special license plate”. Maximum two sim-cards, XX-XX-XXX format. Beach market and private market stall ads omit prices; cheap prices become “for good prices”. Private stalls use listed locations or a house №. Poker bets are at most $5 Million; illegal gambling and dice ads are prohibited.</p>'],
 ['Rejected & blacklisted items','<p>Weapons, ammunition, knives, bulletproof vests/plates and organisation equipment (army uniform, balaclava, EMS masks, medkits, pills): 7 days. Drugs/cannabis: 5 days. Vehicle/people scanners, anti-radar, engine blockers, ropes, headbags, virus USB, lockpicks, bandit masks, counterfeit money, coloured cloth, crowbars, smuggling machine/modules and poison darts: 5 days under the latest internal policy. Bandit gifts: 3 days. Insults to LI and historically controversial figures: 7 days. Troll, sexual/racist and sale-of-people ads: 3–7 days.</p><p>Reject specific family names, gang/nationality mentions, gods, state leaders/deputies, Hype Body Armour, food (fish excepted), birthdays, Grand coins, Battle Pass, weapon/defense cases or gifts, dice/illegal gambling, dangerous razor, tracking sensor and mixed-category ads. Listed clothing skins, accessories and resource scanners are distinct from prohibited equipment.</p><p>Staff must apply punishments and report SELLING illegal items to the appropriate FIB channel. The app does not blacklist anyone.</p>'],
 ['Parties, templates, Services & Discounts','<p>Party location must be specific (including a house number where applicable). Reject parties at state HQs, Government/Capitol, NG/FZ, aircraft carrier, Power Plant, Farm, ghetto, business or beach market. LI Galaxy Rooftop is the stated LI exception. Mega Mall, gang HQs and Black Market cannot be mentioned.</p><p>Service/discount ads must match an active approved LI email template. A discount with a percentage belongs in Discounts; without a percentage, Services. Office, oil well and farm templates go under Work.</p><p>Do not post the same business/office template back-to-back. Wait for three other published ads before repeating it. Internal policy also rejects more than two consecutive template/party ads. This app cannot verify publication history.</p><p>Up to five templates, each up to 150 characters. Verify business ownership, lawyer licence or family leader/deputy proof as appropriate. Previously permanent templates expired on 23 September 2026; standard renewal is $20.000 per week before discounts. Request city/CNN broadcasts, posters, videos and GPS drops via LI ticket services.</p>'],
 ['Work & Dating (staff guidance)','<p>Work uses Hiring / Looking for a job and Salary, even when omitted. Advertise one work role. Experience is “years of experience”, not levels. Construction: site №1 on Vespucci Boulevard, №2 on Calais Avenue, №3 in Pillbox Hill, №4 in Mirror Park. Roles: locksmith, electrician, land worker, surveyor, driver. Lumberjack/farmer/oilman are renamed accordingly in construction ads.</p><p>Other permitted jobs: trucker, lawyer, DJ, photographer/cameraman, bodyguard, professional dancer, oil man, gardener, pilot, collector, firefighter, personal assistant and singer. Salary may be per hour/day.</p><p>Dating supports a person, family/members/diplomacy, friends, wife/husband, girlfriend/boyfriend or date. One named person, full capitalised first/last name, verified in Grand RP or LI Backup City Database. No specific family/nationality or family recruitment. Reject EN1 admins/project/PR/community management and state leaders/deputies. Administration assistants, unofficial-org leaders and crime leaders/deputies are allowed.</p><p>Do not advertise people for sale, spouses with a budget, sugar daddy/mommy, sexual/hookup requests, looking for oneself or offensive/troll names. Follow the internal policy’s additional prohibited dating wording. Proof-of-existence and role checks require LI staff. Work/Dating generation is outside the five creators in this app.</p>'],
 ['Service costs, refunds & staff communication','<p>Mobile ad submission: $3.500 from 10:00–21:00, $5.000 from 21:00–10:00. LI publishes the sender’s full name and mobile number on the board. This creator does not submit ads or charge fees.</p><p>Refund complaints need submitted and published ad screenshots, both showing passport number and time. No refund for prohibited contents, missing people, incomplete/incoherent ads or prices changed to Negotiable for market-value reasons.</p><p>Staff: keep F5 radio on, use it only for work, Senior 1+ correct colleagues calmly, and acknowledge corrections. Always double-check the ad and category before posting.</p>']
];
async function init(){try{const res=await fetch('catalog.json');if(!res.ok)throw Error('Catalogue could not be loaded.');catalog=await res.json();document.getElementById('nav').innerHTML=Object.entries(sections).map(([c,[title]])=>`<li><button type="button" data-category="${c}"><span class="nav-icon" aria-hidden="true">${icons[c]}</span>${title}</button></li>`).join('');document.querySelectorAll('#nav button').forEach(b=>b.addEventListener('click',()=>open(b.dataset.category)));open('vehicle');registerTools();}catch(e){app.textContent=e.message+' Please reload.';}}
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;try{Promise.resolve(context.registerTool({name:'generate_lifeinvader_ad',description:'Validate and generate an ad using the same policy checks as the visible form. Does not post or copy it.',inputSchema:{type:'object',properties:{category:{type:'string',enum:['vehicle','property','business','clothing','items']},data:{type:'object'}},required:['category','data'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!Object.hasOwn(sections,input.category)||input.category==='rules'||!input.data||typeof input.data!=='object')throw Error('Invalid input.');const result=makeAd(input.category,input.data,catalog);category=input.category;state={...defaults(category),...input.data};render();generate();return result;}})).catch(()=>{});}catch{}}
init();
